import '@tanstack/react-router';
import '@tanstack/start-client-core';

/**
 * Type declarations for TanStack Router file-based routing.
 * This registers all API route paths with the router type system.
 *
 * In a production setup, these types would be auto-generated by the
 * TanStack Router plugin. For now, we manually declare the routes
 * to enable type checking.
 */
declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    // UI Routes
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: unknown;
      parentRoute: unknown;
    };
    '/agents/': {
      id: '/agents/';
      path: '/agents';
      fullPath: '/agents/';
      preLoaderRoute: unknown;
      parentRoute: unknown;
    };
    '/agents/$agentId': {
      id: '/agents/$agentId';
      path: '/agents/$agentId';
      fullPath: '/agents/$agentId';
      preLoaderRoute: unknown;
      parentRoute: unknown;
    };
    '/projects/': {
      id: '/projects/';
      path: '/projects';
      fullPath: '/projects/';
      preLoaderRoute: unknown;
      parentRoute: unknown;
    };
    '/projects/$projectId/': {
      id: '/projects/$projectId/';
      path: '/projects/$projectId';
      fullPath: '/projects/$projectId/';
      preLoaderRoute: unknown;
      parentRoute: unknown;
    };
    '/projects/$projectId/tasks/$taskId': {
      id: '/projects/$projectId/tasks/$taskId';
      path: '/projects/$projectId/tasks/$taskId';
      fullPath: '/projects/$projectId/tasks/$taskId';
      preLoaderRoute: unknown;
      parentRoute: unknown;
    };
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId';
      path: '/sessions/$sessionId';
      fullPath: '/sessions/$sessionId';
      preLoaderRoute: unknown;
      parentRoute: unknown;
    };
    // API Routes
    '/api/agents': {
      id: '/api/agents';
      path: '/api/agents';
      fullPath: '/api/agents';
      preLoaderRoute: typeof import('../app/routes/api/agents').Route;
      parentRoute: unknown;
    };
    '/api/agents/$id': {
      id: '/api/agents/$id';
      path: '/api/agents/$id';
      fullPath: '/api/agents/$id';
      preLoaderRoute: typeof import('../app/routes/api/agents/$id').Route;
      parentRoute: unknown;
    };
    '/api/agents/$id/start': {
      id: '/api/agents/$id/start';
      path: '/api/agents/$id/start';
      fullPath: '/api/agents/$id/start';
      preLoaderRoute: typeof import('../app/routes/api/agents/$id/start').Route;
      parentRoute: unknown;
    };
    '/api/agents/$id/status': {
      id: '/api/agents/$id/status';
      path: '/api/agents/$id/status';
      fullPath: '/api/agents/$id/status';
      preLoaderRoute: typeof import('../app/routes/api/agents/$id/status').Route;
      parentRoute: unknown;
    };
    '/api/agents/$id/stop': {
      id: '/api/agents/$id/stop';
      path: '/api/agents/$id/stop';
      fullPath: '/api/agents/$id/stop';
      preLoaderRoute: typeof import('../app/routes/api/agents/$id/stop').Route;
      parentRoute: unknown;
    };
    '/api/projects': {
      id: '/api/projects';
      path: '/api/projects';
      fullPath: '/api/projects';
      preLoaderRoute: typeof import('../app/routes/api/projects').Route;
      parentRoute: unknown;
    };
    '/api/projects/$id': {
      id: '/api/projects/$id';
      path: '/api/projects/$id';
      fullPath: '/api/projects/$id';
      preLoaderRoute: typeof import('../app/routes/api/projects/$id').Route;
      parentRoute: unknown;
    };
    '/api/sessions': {
      id: '/api/sessions';
      path: '/api/sessions';
      fullPath: '/api/sessions';
      preLoaderRoute: typeof import('../app/routes/api/sessions').Route;
      parentRoute: unknown;
    };
    '/api/sessions/$id': {
      id: '/api/sessions/$id';
      path: '/api/sessions/$id';
      fullPath: '/api/sessions/$id';
      preLoaderRoute: typeof import('../app/routes/api/sessions/$id').Route;
      parentRoute: unknown;
    };
    '/api/sessions/$id/close': {
      id: '/api/sessions/$id/close';
      path: '/api/sessions/$id/close';
      fullPath: '/api/sessions/$id/close';
      preLoaderRoute: typeof import('../app/routes/api/sessions/$id/close').Route;
      parentRoute: unknown;
    };
    '/api/sessions/$id/history': {
      id: '/api/sessions/$id/history';
      path: '/api/sessions/$id/history';
      fullPath: '/api/sessions/$id/history';
      preLoaderRoute: typeof import('../app/routes/api/sessions/$id/history').Route;
      parentRoute: unknown;
    };
    '/api/sessions/$id/presence': {
      id: '/api/sessions/$id/presence';
      path: '/api/sessions/$id/presence';
      fullPath: '/api/sessions/$id/presence';
      preLoaderRoute: typeof import('../app/routes/api/sessions/$id/presence').Route;
      parentRoute: unknown;
    };
    '/api/sessions/$id/stream': {
      id: '/api/sessions/$id/stream';
      path: '/api/sessions/$id/stream';
      fullPath: '/api/sessions/$id/stream';
      preLoaderRoute: typeof import('../app/routes/api/sessions/$id/stream').Route;
      parentRoute: unknown;
    };
    '/api/tasks': {
      id: '/api/tasks';
      path: '/api/tasks';
      fullPath: '/api/tasks';
      preLoaderRoute: typeof import('../app/routes/api/tasks').Route;
      parentRoute: unknown;
    };
    '/api/tasks/$id': {
      id: '/api/tasks/$id';
      path: '/api/tasks/$id';
      fullPath: '/api/tasks/$id';
      preLoaderRoute: typeof import('../app/routes/api/tasks/$id').Route;
      parentRoute: unknown;
    };
    '/api/tasks/$id/approve': {
      id: '/api/tasks/$id/approve';
      path: '/api/tasks/$id/approve';
      fullPath: '/api/tasks/$id/approve';
      preLoaderRoute: typeof import('../app/routes/api/tasks/$id/approve').Route;
      parentRoute: unknown;
    };
    '/api/tasks/$id/move': {
      id: '/api/tasks/$id/move';
      path: '/api/tasks/$id/move';
      fullPath: '/api/tasks/$id/move';
      preLoaderRoute: typeof import('../app/routes/api/tasks/$id/move').Route;
      parentRoute: unknown;
    };
    '/api/tasks/$id/reject': {
      id: '/api/tasks/$id/reject';
      path: '/api/tasks/$id/reject';
      fullPath: '/api/tasks/$id/reject';
      preLoaderRoute: typeof import('../app/routes/api/tasks/$id/reject').Route;
      parentRoute: unknown;
    };
  }
}
