/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerraformRouteImport } from './routes/terraform'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CliMonitorRouteImport } from './routes/cli-monitor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorktreesIndexRouteImport } from './routes/worktrees/index'
import { Route as TerraformIndexRouteImport } from './routes/terraform/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as QueueIndexRouteImport } from './routes/queue/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace/index'
import { Route as DesignerIndexRouteImport } from './routes/designer/index'
import { Route as CliMonitorIndexRouteImport } from './routes/cli-monitor/index'
import { Route as CatalogIndexRouteImport } from './routes/catalog/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as TerraformSettingsRouteImport } from './routes/terraform/settings'
import { Route as TerraformModulesRouteImport } from './routes/terraform/modules'
import { Route as TerraformHistoryRouteImport } from './routes/terraform/history'
import { Route as TemplatesProjectRouteImport } from './routes/templates/project'
import { Route as TemplatesOrgRouteImport } from './routes/templates/org'
import { Route as SettingsTerraformRouteImport } from './routes/settings/terraform'
import { Route as SettingsSystemRouteImport } from './routes/settings/system'
import { Route as SettingsSandboxRouteImport } from './routes/settings/sandbox'
import { Route as SettingsPromptsRouteImport } from './routes/settings/prompts'
import { Route as SettingsProjectsRouteImport } from './routes/settings/projects'
import { Route as SettingsPreferencesRouteImport } from './routes/settings/preferences'
import { Route as SettingsModelOptimizationsRouteImport } from './routes/settings/model-optimizations'
import { Route as SettingsGithubRouteImport } from './routes/settings/github'
import { Route as SettingsCliMonitorRouteImport } from './routes/settings/cli-monitor'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as SettingsApiKeysRouteImport } from './routes/settings/api-keys'
import { Route as SettingsAgentsRouteImport } from './routes/settings/agents'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions/$sessionId'
import { Route as CliMonitorTimelineRouteImport } from './routes/cli-monitor/timeline'
import { Route as CliMonitorTerminalRouteImport } from './routes/cli-monitor/terminal'
import { Route as CatalogWorkflowIdRouteImport } from './routes/catalog/$workflowId'
import { Route as AgentsAgentIdRouteImport } from './routes/agents/$agentId'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as TerraformModulesModuleIdRouteImport } from './routes/terraform/modules.$moduleId'
import { Route as ProjectsProjectIdWorktreesRouteImport } from './routes/projects/$projectId/worktrees'
import { Route as ProjectsProjectIdSettingsRouteImport } from './routes/projects/$projectId/settings'
import { Route as ProjectsProjectIdGitRouteImport } from './routes/projects/$projectId/git'
import { Route as ProjectsProjectIdTasksTaskIdRouteImport } from './routes/projects/$projectId/tasks/$taskId'

const TerraformRoute = TerraformRouteImport.update({
  id: '/terraform',
  path: '/terraform',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CliMonitorRoute = CliMonitorRouteImport.update({
  id: '/cli-monitor',
  path: '/cli-monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorktreesIndexRoute = WorktreesIndexRouteImport.update({
  id: '/worktrees/',
  path: '/worktrees/',
  getParentRoute: () => rootRouteImport,
} as any)
const TerraformIndexRoute = TerraformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TerraformRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueIndexRoute = QueueIndexRouteImport.update({
  id: '/queue/',
  path: '/queue/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignerIndexRoute = DesignerIndexRouteImport.update({
  id: '/designer/',
  path: '/designer/',
  getParentRoute: () => rootRouteImport,
} as any)
const CliMonitorIndexRoute = CliMonitorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CliMonitorRoute,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const TerraformSettingsRoute = TerraformSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TerraformRoute,
} as any)
const TerraformModulesRoute = TerraformModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => TerraformRoute,
} as any)
const TerraformHistoryRoute = TerraformHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => TerraformRoute,
} as any)
const TemplatesProjectRoute = TemplatesProjectRouteImport.update({
  id: '/templates/project',
  path: '/templates/project',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesOrgRoute = TemplatesOrgRouteImport.update({
  id: '/templates/org',
  path: '/templates/org',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTerraformRoute = SettingsTerraformRouteImport.update({
  id: '/terraform',
  path: '/terraform',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSystemRoute = SettingsSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSandboxRoute = SettingsSandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPromptsRoute = SettingsPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProjectsRoute = SettingsProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPreferencesRoute = SettingsPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsModelOptimizationsRoute =
  SettingsModelOptimizationsRouteImport.update({
    id: '/model-optimizations',
    path: '/model-optimizations',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsGithubRoute = SettingsGithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCliMonitorRoute = SettingsCliMonitorRouteImport.update({
  id: '/cli-monitor',
  path: '/cli-monitor',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsApiKeysRoute = SettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAgentsRoute = SettingsAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => SettingsRoute,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const CliMonitorTimelineRoute = CliMonitorTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => CliMonitorRoute,
} as any)
const CliMonitorTerminalRoute = CliMonitorTerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => CliMonitorRoute,
} as any)
const CatalogWorkflowIdRoute = CatalogWorkflowIdRouteImport.update({
  id: '/catalog/$workflowId',
  path: '/catalog/$workflowId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/projects/$projectId/',
  path: '/projects/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const TerraformModulesModuleIdRoute =
  TerraformModulesModuleIdRouteImport.update({
    id: '/$moduleId',
    path: '/$moduleId',
    getParentRoute: () => TerraformModulesRoute,
  } as any)
const ProjectsProjectIdWorktreesRoute =
  ProjectsProjectIdWorktreesRouteImport.update({
    id: '/projects/$projectId/worktrees',
    path: '/projects/$projectId/worktrees',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdSettingsRoute =
  ProjectsProjectIdSettingsRouteImport.update({
    id: '/projects/$projectId/settings',
    path: '/projects/$projectId/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdGitRoute = ProjectsProjectIdGitRouteImport.update({
  id: '/projects/$projectId/git',
  path: '/projects/$projectId/git',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdTasksTaskIdRoute =
  ProjectsProjectIdTasksTaskIdRouteImport.update({
    id: '/projects/$projectId/tasks/$taskId',
    path: '/projects/$projectId/tasks/$taskId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cli-monitor': typeof CliMonitorRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/terraform': typeof TerraformRouteWithChildren
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/catalog/$workflowId': typeof CatalogWorkflowIdRoute
  '/cli-monitor/terminal': typeof CliMonitorTerminalRoute
  '/cli-monitor/timeline': typeof CliMonitorTimelineRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/cli-monitor': typeof SettingsCliMonitorRoute
  '/settings/github': typeof SettingsGithubRoute
  '/settings/model-optimizations': typeof SettingsModelOptimizationsRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/projects': typeof SettingsProjectsRoute
  '/settings/prompts': typeof SettingsPromptsRoute
  '/settings/sandbox': typeof SettingsSandboxRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/terraform': typeof SettingsTerraformRoute
  '/templates/org': typeof TemplatesOrgRoute
  '/templates/project': typeof TemplatesProjectRoute
  '/terraform/history': typeof TerraformHistoryRoute
  '/terraform/modules': typeof TerraformModulesRouteWithChildren
  '/terraform/settings': typeof TerraformSettingsRoute
  '/agents/': typeof AgentsIndexRoute
  '/catalog/': typeof CatalogIndexRoute
  '/cli-monitor/': typeof CliMonitorIndexRoute
  '/designer/': typeof DesignerIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/queue/': typeof QueueIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/terraform/': typeof TerraformIndexRoute
  '/worktrees/': typeof WorktreesIndexRoute
  '/projects/$projectId/git': typeof ProjectsProjectIdGitRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/worktrees': typeof ProjectsProjectIdWorktreesRoute
  '/terraform/modules/$moduleId': typeof TerraformModulesModuleIdRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/tasks/$taskId': typeof ProjectsProjectIdTasksTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/catalog/$workflowId': typeof CatalogWorkflowIdRoute
  '/cli-monitor/terminal': typeof CliMonitorTerminalRoute
  '/cli-monitor/timeline': typeof CliMonitorTimelineRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/cli-monitor': typeof SettingsCliMonitorRoute
  '/settings/github': typeof SettingsGithubRoute
  '/settings/model-optimizations': typeof SettingsModelOptimizationsRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/projects': typeof SettingsProjectsRoute
  '/settings/prompts': typeof SettingsPromptsRoute
  '/settings/sandbox': typeof SettingsSandboxRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/terraform': typeof SettingsTerraformRoute
  '/templates/org': typeof TemplatesOrgRoute
  '/templates/project': typeof TemplatesProjectRoute
  '/terraform/history': typeof TerraformHistoryRoute
  '/terraform/modules': typeof TerraformModulesRouteWithChildren
  '/terraform/settings': typeof TerraformSettingsRoute
  '/agents': typeof AgentsIndexRoute
  '/catalog': typeof CatalogIndexRoute
  '/cli-monitor': typeof CliMonitorIndexRoute
  '/designer': typeof DesignerIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/queue': typeof QueueIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/terraform': typeof TerraformIndexRoute
  '/worktrees': typeof WorktreesIndexRoute
  '/projects/$projectId/git': typeof ProjectsProjectIdGitRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/worktrees': typeof ProjectsProjectIdWorktreesRoute
  '/terraform/modules/$moduleId': typeof TerraformModulesModuleIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/tasks/$taskId': typeof ProjectsProjectIdTasksTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cli-monitor': typeof CliMonitorRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/terraform': typeof TerraformRouteWithChildren
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/catalog/$workflowId': typeof CatalogWorkflowIdRoute
  '/cli-monitor/terminal': typeof CliMonitorTerminalRoute
  '/cli-monitor/timeline': typeof CliMonitorTimelineRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/cli-monitor': typeof SettingsCliMonitorRoute
  '/settings/github': typeof SettingsGithubRoute
  '/settings/model-optimizations': typeof SettingsModelOptimizationsRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/projects': typeof SettingsProjectsRoute
  '/settings/prompts': typeof SettingsPromptsRoute
  '/settings/sandbox': typeof SettingsSandboxRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/terraform': typeof SettingsTerraformRoute
  '/templates/org': typeof TemplatesOrgRoute
  '/templates/project': typeof TemplatesProjectRoute
  '/terraform/history': typeof TerraformHistoryRoute
  '/terraform/modules': typeof TerraformModulesRouteWithChildren
  '/terraform/settings': typeof TerraformSettingsRoute
  '/agents/': typeof AgentsIndexRoute
  '/catalog/': typeof CatalogIndexRoute
  '/cli-monitor/': typeof CliMonitorIndexRoute
  '/designer/': typeof DesignerIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/queue/': typeof QueueIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/terraform/': typeof TerraformIndexRoute
  '/worktrees/': typeof WorktreesIndexRoute
  '/projects/$projectId/git': typeof ProjectsProjectIdGitRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/worktrees': typeof ProjectsProjectIdWorktreesRoute
  '/terraform/modules/$moduleId': typeof TerraformModulesModuleIdRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/tasks/$taskId': typeof ProjectsProjectIdTasksTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cli-monitor'
    | '/settings'
    | '/terraform'
    | '/agents/$agentId'
    | '/catalog/$workflowId'
    | '/cli-monitor/terminal'
    | '/cli-monitor/timeline'
    | '/sessions/$sessionId'
    | '/settings/agents'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/cli-monitor'
    | '/settings/github'
    | '/settings/model-optimizations'
    | '/settings/preferences'
    | '/settings/projects'
    | '/settings/prompts'
    | '/settings/sandbox'
    | '/settings/system'
    | '/settings/terraform'
    | '/templates/org'
    | '/templates/project'
    | '/terraform/history'
    | '/terraform/modules'
    | '/terraform/settings'
    | '/agents/'
    | '/catalog/'
    | '/cli-monitor/'
    | '/designer/'
    | '/marketplace/'
    | '/projects/'
    | '/queue/'
    | '/sessions/'
    | '/settings/'
    | '/terraform/'
    | '/worktrees/'
    | '/projects/$projectId/git'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/worktrees'
    | '/terraform/modules/$moduleId'
    | '/projects/$projectId/'
    | '/projects/$projectId/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents/$agentId'
    | '/catalog/$workflowId'
    | '/cli-monitor/terminal'
    | '/cli-monitor/timeline'
    | '/sessions/$sessionId'
    | '/settings/agents'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/cli-monitor'
    | '/settings/github'
    | '/settings/model-optimizations'
    | '/settings/preferences'
    | '/settings/projects'
    | '/settings/prompts'
    | '/settings/sandbox'
    | '/settings/system'
    | '/settings/terraform'
    | '/templates/org'
    | '/templates/project'
    | '/terraform/history'
    | '/terraform/modules'
    | '/terraform/settings'
    | '/agents'
    | '/catalog'
    | '/cli-monitor'
    | '/designer'
    | '/marketplace'
    | '/projects'
    | '/queue'
    | '/sessions'
    | '/settings'
    | '/terraform'
    | '/worktrees'
    | '/projects/$projectId/git'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/worktrees'
    | '/terraform/modules/$moduleId'
    | '/projects/$projectId'
    | '/projects/$projectId/tasks/$taskId'
  id:
    | '__root__'
    | '/'
    | '/cli-monitor'
    | '/settings'
    | '/terraform'
    | '/agents/$agentId'
    | '/catalog/$workflowId'
    | '/cli-monitor/terminal'
    | '/cli-monitor/timeline'
    | '/sessions/$sessionId'
    | '/settings/agents'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/cli-monitor'
    | '/settings/github'
    | '/settings/model-optimizations'
    | '/settings/preferences'
    | '/settings/projects'
    | '/settings/prompts'
    | '/settings/sandbox'
    | '/settings/system'
    | '/settings/terraform'
    | '/templates/org'
    | '/templates/project'
    | '/terraform/history'
    | '/terraform/modules'
    | '/terraform/settings'
    | '/agents/'
    | '/catalog/'
    | '/cli-monitor/'
    | '/designer/'
    | '/marketplace/'
    | '/projects/'
    | '/queue/'
    | '/sessions/'
    | '/settings/'
    | '/terraform/'
    | '/worktrees/'
    | '/projects/$projectId/git'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/worktrees'
    | '/terraform/modules/$moduleId'
    | '/projects/$projectId/'
    | '/projects/$projectId/tasks/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CliMonitorRoute: typeof CliMonitorRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  TerraformRoute: typeof TerraformRouteWithChildren
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
  CatalogWorkflowIdRoute: typeof CatalogWorkflowIdRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  TemplatesOrgRoute: typeof TemplatesOrgRoute
  TemplatesProjectRoute: typeof TemplatesProjectRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
  DesignerIndexRoute: typeof DesignerIndexRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  QueueIndexRoute: typeof QueueIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  WorktreesIndexRoute: typeof WorktreesIndexRoute
  ProjectsProjectIdGitRoute: typeof ProjectsProjectIdGitRoute
  ProjectsProjectIdSettingsRoute: typeof ProjectsProjectIdSettingsRoute
  ProjectsProjectIdWorktreesRoute: typeof ProjectsProjectIdWorktreesRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  ProjectsProjectIdTasksTaskIdRoute: typeof ProjectsProjectIdTasksTaskIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terraform': {
      id: '/terraform'
      path: '/terraform'
      fullPath: '/terraform'
      preLoaderRoute: typeof TerraformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli-monitor': {
      id: '/cli-monitor'
      path: '/cli-monitor'
      fullPath: '/cli-monitor'
      preLoaderRoute: typeof CliMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worktrees/': {
      id: '/worktrees/'
      path: '/worktrees'
      fullPath: '/worktrees/'
      preLoaderRoute: typeof WorktreesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terraform/': {
      id: '/terraform/'
      path: '/'
      fullPath: '/terraform/'
      preLoaderRoute: typeof TerraformIndexRouteImport
      parentRoute: typeof TerraformRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue/': {
      id: '/queue/'
      path: '/queue'
      fullPath: '/queue/'
      preLoaderRoute: typeof QueueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designer/': {
      id: '/designer/'
      path: '/designer'
      fullPath: '/designer/'
      preLoaderRoute: typeof DesignerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli-monitor/': {
      id: '/cli-monitor/'
      path: '/'
      fullPath: '/cli-monitor/'
      preLoaderRoute: typeof CliMonitorIndexRouteImport
      parentRoute: typeof CliMonitorRoute
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terraform/settings': {
      id: '/terraform/settings'
      path: '/settings'
      fullPath: '/terraform/settings'
      preLoaderRoute: typeof TerraformSettingsRouteImport
      parentRoute: typeof TerraformRoute
    }
    '/terraform/modules': {
      id: '/terraform/modules'
      path: '/modules'
      fullPath: '/terraform/modules'
      preLoaderRoute: typeof TerraformModulesRouteImport
      parentRoute: typeof TerraformRoute
    }
    '/terraform/history': {
      id: '/terraform/history'
      path: '/history'
      fullPath: '/terraform/history'
      preLoaderRoute: typeof TerraformHistoryRouteImport
      parentRoute: typeof TerraformRoute
    }
    '/templates/project': {
      id: '/templates/project'
      path: '/templates/project'
      fullPath: '/templates/project'
      preLoaderRoute: typeof TemplatesProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/org': {
      id: '/templates/org'
      path: '/templates/org'
      fullPath: '/templates/org'
      preLoaderRoute: typeof TemplatesOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/terraform': {
      id: '/settings/terraform'
      path: '/terraform'
      fullPath: '/settings/terraform'
      preLoaderRoute: typeof SettingsTerraformRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/system': {
      id: '/settings/system'
      path: '/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof SettingsSystemRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/sandbox': {
      id: '/settings/sandbox'
      path: '/sandbox'
      fullPath: '/settings/sandbox'
      preLoaderRoute: typeof SettingsSandboxRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/prompts': {
      id: '/settings/prompts'
      path: '/prompts'
      fullPath: '/settings/prompts'
      preLoaderRoute: typeof SettingsPromptsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/projects': {
      id: '/settings/projects'
      path: '/projects'
      fullPath: '/settings/projects'
      preLoaderRoute: typeof SettingsProjectsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/preferences': {
      id: '/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof SettingsPreferencesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/model-optimizations': {
      id: '/settings/model-optimizations'
      path: '/model-optimizations'
      fullPath: '/settings/model-optimizations'
      preLoaderRoute: typeof SettingsModelOptimizationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/github': {
      id: '/settings/github'
      path: '/github'
      fullPath: '/settings/github'
      preLoaderRoute: typeof SettingsGithubRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/cli-monitor': {
      id: '/settings/cli-monitor'
      path: '/cli-monitor'
      fullPath: '/settings/cli-monitor'
      preLoaderRoute: typeof SettingsCliMonitorRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/api-keys': {
      id: '/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof SettingsApiKeysRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/agents': {
      id: '/settings/agents'
      path: '/agents'
      fullPath: '/settings/agents'
      preLoaderRoute: typeof SettingsAgentsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli-monitor/timeline': {
      id: '/cli-monitor/timeline'
      path: '/timeline'
      fullPath: '/cli-monitor/timeline'
      preLoaderRoute: typeof CliMonitorTimelineRouteImport
      parentRoute: typeof CliMonitorRoute
    }
    '/cli-monitor/terminal': {
      id: '/cli-monitor/terminal'
      path: '/terminal'
      fullPath: '/cli-monitor/terminal'
      preLoaderRoute: typeof CliMonitorTerminalRouteImport
      parentRoute: typeof CliMonitorRoute
    }
    '/catalog/$workflowId': {
      id: '/catalog/$workflowId'
      path: '/catalog/$workflowId'
      fullPath: '/catalog/$workflowId'
      preLoaderRoute: typeof CatalogWorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terraform/modules/$moduleId': {
      id: '/terraform/modules/$moduleId'
      path: '/$moduleId'
      fullPath: '/terraform/modules/$moduleId'
      preLoaderRoute: typeof TerraformModulesModuleIdRouteImport
      parentRoute: typeof TerraformModulesRoute
    }
    '/projects/$projectId/worktrees': {
      id: '/projects/$projectId/worktrees'
      path: '/projects/$projectId/worktrees'
      fullPath: '/projects/$projectId/worktrees'
      preLoaderRoute: typeof ProjectsProjectIdWorktreesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/settings': {
      id: '/projects/$projectId/settings'
      path: '/projects/$projectId/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ProjectsProjectIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/git': {
      id: '/projects/$projectId/git'
      path: '/projects/$projectId/git'
      fullPath: '/projects/$projectId/git'
      preLoaderRoute: typeof ProjectsProjectIdGitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/tasks/$taskId': {
      id: '/projects/$projectId/tasks/$taskId'
      path: '/projects/$projectId/tasks/$taskId'
      fullPath: '/projects/$projectId/tasks/$taskId'
      preLoaderRoute: typeof ProjectsProjectIdTasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CliMonitorRouteChildren {
  CliMonitorTerminalRoute: typeof CliMonitorTerminalRoute
  CliMonitorTimelineRoute: typeof CliMonitorTimelineRoute
  CliMonitorIndexRoute: typeof CliMonitorIndexRoute
}

const CliMonitorRouteChildren: CliMonitorRouteChildren = {
  CliMonitorTerminalRoute: CliMonitorTerminalRoute,
  CliMonitorTimelineRoute: CliMonitorTimelineRoute,
  CliMonitorIndexRoute: CliMonitorIndexRoute,
}

const CliMonitorRouteWithChildren = CliMonitorRoute._addFileChildren(
  CliMonitorRouteChildren,
)

interface SettingsRouteChildren {
  SettingsAgentsRoute: typeof SettingsAgentsRoute
  SettingsApiKeysRoute: typeof SettingsApiKeysRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsCliMonitorRoute: typeof SettingsCliMonitorRoute
  SettingsGithubRoute: typeof SettingsGithubRoute
  SettingsModelOptimizationsRoute: typeof SettingsModelOptimizationsRoute
  SettingsPreferencesRoute: typeof SettingsPreferencesRoute
  SettingsProjectsRoute: typeof SettingsProjectsRoute
  SettingsPromptsRoute: typeof SettingsPromptsRoute
  SettingsSandboxRoute: typeof SettingsSandboxRoute
  SettingsSystemRoute: typeof SettingsSystemRoute
  SettingsTerraformRoute: typeof SettingsTerraformRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAgentsRoute: SettingsAgentsRoute,
  SettingsApiKeysRoute: SettingsApiKeysRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsCliMonitorRoute: SettingsCliMonitorRoute,
  SettingsGithubRoute: SettingsGithubRoute,
  SettingsModelOptimizationsRoute: SettingsModelOptimizationsRoute,
  SettingsPreferencesRoute: SettingsPreferencesRoute,
  SettingsProjectsRoute: SettingsProjectsRoute,
  SettingsPromptsRoute: SettingsPromptsRoute,
  SettingsSandboxRoute: SettingsSandboxRoute,
  SettingsSystemRoute: SettingsSystemRoute,
  SettingsTerraformRoute: SettingsTerraformRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface TerraformModulesRouteChildren {
  TerraformModulesModuleIdRoute: typeof TerraformModulesModuleIdRoute
}

const TerraformModulesRouteChildren: TerraformModulesRouteChildren = {
  TerraformModulesModuleIdRoute: TerraformModulesModuleIdRoute,
}

const TerraformModulesRouteWithChildren =
  TerraformModulesRoute._addFileChildren(TerraformModulesRouteChildren)

interface TerraformRouteChildren {
  TerraformHistoryRoute: typeof TerraformHistoryRoute
  TerraformModulesRoute: typeof TerraformModulesRouteWithChildren
  TerraformSettingsRoute: typeof TerraformSettingsRoute
  TerraformIndexRoute: typeof TerraformIndexRoute
}

const TerraformRouteChildren: TerraformRouteChildren = {
  TerraformHistoryRoute: TerraformHistoryRoute,
  TerraformModulesRoute: TerraformModulesRouteWithChildren,
  TerraformSettingsRoute: TerraformSettingsRoute,
  TerraformIndexRoute: TerraformIndexRoute,
}

const TerraformRouteWithChildren = TerraformRoute._addFileChildren(
  TerraformRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CliMonitorRoute: CliMonitorRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  TerraformRoute: TerraformRouteWithChildren,
  AgentsAgentIdRoute: AgentsAgentIdRoute,
  CatalogWorkflowIdRoute: CatalogWorkflowIdRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  TemplatesOrgRoute: TemplatesOrgRoute,
  TemplatesProjectRoute: TemplatesProjectRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  CatalogIndexRoute: CatalogIndexRoute,
  DesignerIndexRoute: DesignerIndexRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  QueueIndexRoute: QueueIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  WorktreesIndexRoute: WorktreesIndexRoute,
  ProjectsProjectIdGitRoute: ProjectsProjectIdGitRoute,
  ProjectsProjectIdSettingsRoute: ProjectsProjectIdSettingsRoute,
  ProjectsProjectIdWorktreesRoute: ProjectsProjectIdWorktreesRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
  ProjectsProjectIdTasksTaskIdRoute: ProjectsProjectIdTasksTaskIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
