/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by TanStack Router

import '@tanstack/start-client-core';
import { Route as rootRoute } from './routes/__root';
import { Route as AgentsAgentIdRoute } from './routes/agents/$agentId';
import { Route as AgentsIndexRoute } from './routes/agents/index';
import { Route as IndexRoute } from './routes/index';
import { Route as ProjectsProjectIdIndexRoute } from './routes/projects/$projectId/index';
import type { Route as ProjectsProjectIdTasksTaskIdRoute } from './routes/projects/$projectId/tasks/$taskId';
import { Route as ProjectsIndexRoute } from './routes/projects/index';
import { Route as QueueIndexRoute } from './routes/queue/index';
import { Route as SessionsSessionIdRoute } from './routes/sessions/$sessionId';
import { Route as SessionsIndexRoute } from './routes/sessions/index';
import { Route as SettingsIndexRoute } from './routes/settings/index';
import { Route as WorktreesIndexRoute } from './routes/worktrees/index';

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRoute;
      parentRoute: typeof rootRoute;
    };
    '/projects/': {
      id: '/projects/';
      path: '/projects';
      fullPath: '/projects';
      preLoaderRoute: typeof ProjectsIndexRoute;
      parentRoute: typeof rootRoute;
    };
    '/agents/': {
      id: '/agents/';
      path: '/agents';
      fullPath: '/agents';
      preLoaderRoute: typeof AgentsIndexRoute;
      parentRoute: typeof rootRoute;
    };
    '/projects/$projectId': {
      id: '/projects/$projectId/';
      path: '/projects/$projectId';
      fullPath: '/projects/$projectId';
      preLoaderRoute: typeof ProjectsProjectIdIndexRoute;
      parentRoute: typeof rootRoute;
    };
    '/projects/$projectId/': {
      id: '/projects/$projectId/';
      path: '/projects/$projectId';
      fullPath: '/projects/$projectId';
      preLoaderRoute: typeof ProjectsProjectIdIndexRoute;
      parentRoute: typeof rootRoute;
    };
    '/agents/$agentId': {
      id: '/agents/$agentId';
      path: '/agents/$agentId';
      fullPath: '/agents/$agentId';
      preLoaderRoute: typeof AgentsAgentIdRoute;
      parentRoute: typeof rootRoute;
    };
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId';
      path: '/sessions/$sessionId';
      fullPath: '/sessions/$sessionId';
      preLoaderRoute: typeof SessionsSessionIdRoute;
      parentRoute: typeof rootRoute;
    };
    '/queue': {
      id: '/queue/';
      path: '/queue';
      fullPath: '/queue';
      preLoaderRoute: typeof QueueIndexRoute;
      parentRoute: typeof rootRoute;
    };
    '/sessions': {
      id: '/sessions/';
      path: '/sessions';
      fullPath: '/sessions';
      preLoaderRoute: typeof SessionsIndexRoute;
      parentRoute: typeof rootRoute;
    };
    '/settings': {
      id: '/settings/';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof SettingsIndexRoute;
      parentRoute: typeof rootRoute;
    };
    '/worktrees': {
      id: '/worktrees/';
      path: '/worktrees';
      fullPath: '/worktrees';
      preLoaderRoute: typeof WorktreesIndexRoute;
      parentRoute: typeof rootRoute;
    };
    '/projects/$projectId/tasks/$taskId': {
      id: '/projects/$projectId/tasks/$taskId';
      path: '/projects/$projectId/tasks/$taskId';
      fullPath: '/projects/$projectId/tasks/$taskId';
      preLoaderRoute: typeof ProjectsProjectIdTasksTaskIdRoute;
      parentRoute: typeof rootRoute;
    };
    // API routes
    '/api/agents': {
      id: '/api/agents';
      path: '/api/agents';
      fullPath: '/api/agents';
      preLoaderRoute: unknown;
      parentRoute: typeof rootRoute;
    };
    '/api/agents/$id': {
      id: '/api/agents/$id';
      path: '/api/agents/$id';
      fullPath: '/api/agents/$id';
      preLoaderRoute: unknown;
      parentRoute: typeof rootRoute;
    };
    '/api/agents/$id/start': {
      id: '/api/agents/$id/start';
      path: '/api/agents/$id/start';
      fullPath: '/api/agents/$id/start';
      preLoaderRoute: unknown;
      parentRoute: typeof rootRoute;
    };
    '/api/agents/$id/status': {
      id: '/api/agents/$id/status';
      path: '/api/agents/$id/status';
      fullPath: '/api/agents/$id/status';
      preLoaderRoute: unknown;
      parentRoute: typeof rootRoute;
    };
    '/api/agents/$id/stop': {
      id: '/api/agents/$id/stop';
      path: '/api/agents/$id/stop';
      fullPath: '/api/agents/$id/stop';
      preLoaderRoute: unknown;
      parentRoute: typeof rootRoute;
    };
    '/api/projects': {
      id: '/api/projects';
      path: '/api/projects';
      fullPath: '/api/projects';
      preLoaderRoute: unknown;
      parentRoute: typeof rootRoute;
    };
    '/api/projects/$id': {
      id: '/api/projects/$id';
      path: '/api/projects/$id';
      fullPath: '/api/projects/$id';
      preLoaderRoute: unknown;
      parentRoute: typeof rootRoute;
    };
    '/api/sessions': {
      id: '/api/sessions';
      path: '/api/sessions';
      fullPath: '/api/sessions';
      preLoaderRoute: unknown;
      parentRoute: typeof rootRoute;
    };
    '/api/sessions/$id': {
      id: '/api/sessions/$id';
      path: '/api/sessions/$id';
      fullPath: '/api/sessions/$id';
      preLoaderRoute: unknown;
      parentRoute: typeof rootRoute;
    };
    '/api/sessions/$id/close': {
      id: '/api/sessions/$id/close';
      path: '/api/sessions/$id/close';
      fullPath: '/api/sessions/$id/close';
      preLoaderRoute: unknown;
      parentRoute: typeof rootRoute;
    };
    '/api/sessions/$id/history': {
      id: '/api/sessions/$id/history';
      path: '/api/sessions/$id/history';
      fullPath: '/api/sessions/$id/history';
      preLoaderRoute: unknown;
      parentRoute: typeof rootRoute;
    };
    '/api/sessions/$id/presence': {
      id: '/api/sessions/$id/presence';
      path: '/api/sessions/$id/presence';
      fullPath: '/api/sessions/$id/presence';
      preLoaderRoute: unknown;
      parentRoute: typeof rootRoute;
    };
    '/api/sessions/$id/stream': {
      id: '/api/sessions/$id/stream';
      path: '/api/sessions/$id/stream';
      fullPath: '/api/sessions/$id/stream';
      preLoaderRoute: unknown;
      parentRoute: typeof rootRoute;
    };
    '/api/tasks': {
      id: '/api/tasks';
      path: '/api/tasks';
      fullPath: '/api/tasks';
      preLoaderRoute: unknown;
      parentRoute: typeof rootRoute;
    };
    '/api/tasks/$id': {
      id: '/api/tasks/$id';
      path: '/api/tasks/$id';
      fullPath: '/api/tasks/$id';
      preLoaderRoute: unknown;
      parentRoute: typeof rootRoute;
    };
    '/api/tasks/$id/approve': {
      id: '/api/tasks/$id/approve';
      path: '/api/tasks/$id/approve';
      fullPath: '/api/tasks/$id/approve';
      preLoaderRoute: unknown;
      parentRoute: typeof rootRoute;
    };
    '/api/tasks/$id/move': {
      id: '/api/tasks/$id/move';
      path: '/api/tasks/$id/move';
      fullPath: '/api/tasks/$id/move';
      preLoaderRoute: unknown;
      parentRoute: typeof rootRoute;
    };
    '/api/tasks/$id/reject': {
      id: '/api/tasks/$id/reject';
      path: '/api/tasks/$id/reject';
      fullPath: '/api/tasks/$id/reject';
      preLoaderRoute: unknown;
      parentRoute: typeof rootRoute;
    };
    '/api/agents/$id/pause': {
      id: '/api/agents/$id/pause';
      path: '/api/agents/$id/pause';
      fullPath: '/api/agents/$id/pause';
      preLoaderRoute: unknown;
      parentRoute: typeof rootRoute;
    };
    '/api/agents/$id/resume': {
      id: '/api/agents/$id/resume';
      path: '/api/agents/$id/resume';
      fullPath: '/api/agents/$id/resume';
      preLoaderRoute: unknown;
      parentRoute: typeof rootRoute;
    };
    '/api/webhooks/github': {
      id: '/api/webhooks/github';
      path: '/api/webhooks/github';
      fullPath: '/api/webhooks/github';
      preLoaderRoute: unknown;
      parentRoute: typeof rootRoute;
    };
    '/api/worktrees/': {
      id: '/api/worktrees/';
      path: '/api/worktrees/';
      fullPath: '/api/worktrees/';
      preLoaderRoute: unknown;
      parentRoute: typeof rootRoute;
    };
    '/api/worktrees/$id': {
      id: '/api/worktrees/$id';
      path: '/api/worktrees/$id';
      fullPath: '/api/worktrees/$id';
      preLoaderRoute: unknown;
      parentRoute: typeof rootRoute;
    };
    '/api/worktrees/$id/commit': {
      id: '/api/worktrees/$id/commit';
      path: '/api/worktrees/$id/commit';
      fullPath: '/api/worktrees/$id/commit';
      preLoaderRoute: unknown;
      parentRoute: typeof rootRoute;
    };
    '/api/worktrees/$id/diff': {
      id: '/api/worktrees/$id/diff';
      path: '/api/worktrees/$id/diff';
      fullPath: '/api/worktrees/$id/diff';
      preLoaderRoute: unknown;
      parentRoute: typeof rootRoute;
    };
    '/api/worktrees/$id/merge': {
      id: '/api/worktrees/$id/merge';
      path: '/api/worktrees/$id/merge';
      fullPath: '/api/worktrees/$id/merge';
      preLoaderRoute: unknown;
      parentRoute: typeof rootRoute;
    };
    '/api/worktrees/prune': {
      id: '/api/worktrees/prune';
      path: '/api/worktrees/prune';
      fullPath: '/api/worktrees/prune';
      preLoaderRoute: unknown;
      parentRoute: typeof rootRoute;
    };
  }
}

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/projects': typeof ProjectsIndexRoute;
  '/agents': typeof AgentsIndexRoute;
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute;
  '/agents/$agentId': typeof AgentsAgentIdRoute;
  '/sessions/$sessionId': typeof SessionsSessionIdRoute;
  '/queue': typeof QueueIndexRoute;
  '/sessions': typeof SessionsIndexRoute;
  '/settings': typeof SettingsIndexRoute;
  '/worktrees': typeof WorktreesIndexRoute;
  '/projects/$projectId/tasks/$taskId': typeof ProjectsProjectIdTasksTaskIdRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/projects': typeof ProjectsIndexRoute;
  '/agents': typeof AgentsIndexRoute;
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute;
  '/agents/$agentId': typeof AgentsAgentIdRoute;
  '/sessions/$sessionId': typeof SessionsSessionIdRoute;
  '/queue': typeof QueueIndexRoute;
  '/sessions': typeof SessionsIndexRoute;
  '/settings': typeof SettingsIndexRoute;
  '/worktrees': typeof WorktreesIndexRoute;
  '/projects/$projectId/tasks/$taskId': typeof ProjectsProjectIdTasksTaskIdRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/projects/': typeof ProjectsIndexRoute;
  '/agents/': typeof AgentsIndexRoute;
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute;
  '/agents/$agentId': typeof AgentsAgentIdRoute;
  '/sessions/$sessionId': typeof SessionsSessionIdRoute;
  '/queue/': typeof QueueIndexRoute;
  '/sessions/': typeof SessionsIndexRoute;
  '/settings/': typeof SettingsIndexRoute;
  '/worktrees/': typeof WorktreesIndexRoute;
  '/projects/$projectId/tasks/$taskId': typeof ProjectsProjectIdTasksTaskIdRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/projects'
    | '/agents'
    | '/projects/$projectId'
    | '/agents/$agentId'
    | '/sessions/$sessionId'
    | '/queue'
    | '/sessions'
    | '/settings'
    | '/worktrees'
    | '/projects/$projectId/tasks/$taskId';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/projects'
    | '/agents'
    | '/projects/$projectId'
    | '/agents/$agentId'
    | '/sessions/$sessionId'
    | '/queue'
    | '/sessions'
    | '/settings'
    | '/worktrees'
    | '/projects/$projectId/tasks/$taskId';
  id:
    | '__root__'
    | '/'
    | '/projects/'
    | '/agents/'
    | '/projects/$projectId/'
    | '/agents/$agentId'
    | '/sessions/$sessionId'
    | '/queue/'
    | '/sessions/'
    | '/settings/'
    | '/worktrees/'
    | '/projects/$projectId/tasks/$taskId';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ProjectsIndexRoute: typeof ProjectsIndexRoute;
  AgentsIndexRoute: typeof AgentsIndexRoute;
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute;
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute;
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute;
  QueueIndexRoute: typeof QueueIndexRoute;
  SessionsIndexRoute: typeof SessionsIndexRoute;
  SettingsIndexRoute: typeof SettingsIndexRoute;
  WorktreesIndexRoute: typeof WorktreesIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  ProjectsIndexRoute,
  AgentsIndexRoute,
  ProjectsProjectIdIndexRoute,
  AgentsAgentIdRoute,
  SessionsSessionIdRoute,
  QueueIndexRoute,
  SessionsIndexRoute,
  SettingsIndexRoute,
  WorktreesIndexRoute,
};

export const routeTree = rootRoute._addFileChildren(rootRouteChildren);
