/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by TanStack Router

import { Route as rootRoute } from './routes/__root';
import { Route as IndexRoute } from './routes/index';
import { Route as ProjectsIndexRoute } from './routes/projects/index';
import { Route as AgentsIndexRoute } from './routes/agents/index';
import { Route as ProjectsProjectIdIndexRoute } from './routes/projects/$projectId/index';
import { Route as AgentsAgentIdRoute } from './routes/agents/$agentId';
import { Route as SessionsSessionIdRoute } from './routes/sessions/$sessionId';
import { Route as ProjectsProjectIdTasksTaskIdRoute } from './routes/projects/$projectId/tasks/$taskId';

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRoute;
      parentRoute: typeof rootRoute;
    };
    '/projects/': {
      id: '/projects/';
      path: '/projects';
      fullPath: '/projects';
      preLoaderRoute: typeof ProjectsIndexRoute;
      parentRoute: typeof rootRoute;
    };
    '/agents/': {
      id: '/agents/';
      path: '/agents';
      fullPath: '/agents';
      preLoaderRoute: typeof AgentsIndexRoute;
      parentRoute: typeof rootRoute;
    };
    '/projects/$projectId': {
      id: '/projects/$projectId/';
      path: '/projects/$projectId';
      fullPath: '/projects/$projectId';
      preLoaderRoute: typeof ProjectsProjectIdIndexRoute;
      parentRoute: typeof rootRoute;
    };
    '/projects/$projectId/': {
      id: '/projects/$projectId/';
      path: '/projects/$projectId';
      fullPath: '/projects/$projectId';
      preLoaderRoute: typeof ProjectsProjectIdIndexRoute;
      parentRoute: typeof rootRoute;
    };
    '/agents/$agentId': {
      id: '/agents/$agentId';
      path: '/agents/$agentId';
      fullPath: '/agents/$agentId';
      preLoaderRoute: typeof AgentsAgentIdRoute;
      parentRoute: typeof rootRoute;
    };
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId';
      path: '/sessions/$sessionId';
      fullPath: '/sessions/$sessionId';
      preLoaderRoute: typeof SessionsSessionIdRoute;
      parentRoute: typeof rootRoute;
    };
    '/projects/$projectId/tasks/$taskId': {
      id: '/projects/$projectId/tasks/$taskId';
      path: '/projects/$projectId/tasks/$taskId';
      fullPath: '/projects/$projectId/tasks/$taskId';
      preLoaderRoute: typeof ProjectsProjectIdTasksTaskIdRoute;
      parentRoute: typeof rootRoute;
    };
  }
}

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/projects': typeof ProjectsIndexRoute;
  '/agents': typeof AgentsIndexRoute;
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute;
  '/agents/$agentId': typeof AgentsAgentIdRoute;
  '/sessions/$sessionId': typeof SessionsSessionIdRoute;
  '/projects/$projectId/tasks/$taskId': typeof ProjectsProjectIdTasksTaskIdRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/projects': typeof ProjectsIndexRoute;
  '/agents': typeof AgentsIndexRoute;
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute;
  '/agents/$agentId': typeof AgentsAgentIdRoute;
  '/sessions/$sessionId': typeof SessionsSessionIdRoute;
  '/projects/$projectId/tasks/$taskId': typeof ProjectsProjectIdTasksTaskIdRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/projects/': typeof ProjectsIndexRoute;
  '/agents/': typeof AgentsIndexRoute;
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute;
  '/agents/$agentId': typeof AgentsAgentIdRoute;
  '/sessions/$sessionId': typeof SessionsSessionIdRoute;
  '/projects/$projectId/tasks/$taskId': typeof ProjectsProjectIdTasksTaskIdRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/projects'
    | '/agents'
    | '/projects/$projectId'
    | '/agents/$agentId'
    | '/sessions/$sessionId'
    | '/projects/$projectId/tasks/$taskId';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/projects'
    | '/agents'
    | '/projects/$projectId'
    | '/agents/$agentId'
    | '/sessions/$sessionId'
    | '/projects/$projectId/tasks/$taskId';
  id:
    | '__root__'
    | '/'
    | '/projects/'
    | '/agents/'
    | '/projects/$projectId/'
    | '/agents/$agentId'
    | '/sessions/$sessionId'
    | '/projects/$projectId/tasks/$taskId';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ProjectsIndexRoute: typeof ProjectsIndexRoute;
  AgentsIndexRoute: typeof AgentsIndexRoute;
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute;
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute;
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  ProjectsIndexRoute,
  AgentsIndexRoute,
  ProjectsProjectIdIndexRoute,
  AgentsAgentIdRoute,
  SessionsSessionIdRoute,
};

export const routeTree = rootRoute._addFileChildren(rootRouteChildren);
