import {
  ArrowsLeftRight,
  Calendar,
  Clock,
  Image as ImageIcon,
  Robot,
  Tag,
  Trash,
} from '@phosphor-icons/react';
import { cva } from 'class-variance-authority';
import { Button } from '@/app/components/ui/button';
import type { Workflow } from '@/db/schema/workflows';
import { cn } from '@/lib/utils/cn';

// =============================================================================
// Types
// =============================================================================

export interface WorkflowCardProps {
  workflow: Workflow;
  isSelected?: boolean;
  onClick: () => void;
  onDelete?: () => void;
}

// =============================================================================
// Styles
// =============================================================================

const cardVariants = cva(
  'group relative rounded-lg border bg-surface overflow-hidden transition-all duration-150 cursor-pointer',
  {
    variants: {
      state: {
        default: 'border-border hover:border-fg-subtle hover:shadow-md',
        selected: 'border-accent ring-2 ring-accent-muted shadow-md',
      },
    },
    defaultVariants: {
      state: 'default',
    },
  }
);

const statusBadgeVariants = cva(
  'inline-flex items-center gap-1 h-5 px-2 text-xs font-medium rounded-full border shrink-0',
  {
    variants: {
      status: {
        draft: 'bg-surface-muted text-fg-muted border-border',
        published: 'bg-success-muted text-success border-success/40',
        archived: 'bg-attention-muted text-attention border-attention/40',
      },
    },
    defaultVariants: {
      status: 'draft',
    },
  }
);

// =============================================================================
// Helper Functions
// =============================================================================

function formatRelativeTime(date: Date | string | null | undefined): string {
  if (!date) return 'Never';
  const now = Date.now();
  const dateObj = typeof date === 'string' ? new Date(date) : date;
  const diff = now - dateObj.getTime();
  const hours = Math.floor(diff / (1000 * 60 * 60));
  const minutes = Math.floor(diff / (1000 * 60));

  if (hours > 24) return `${Math.floor(hours / 24)}d ago`;
  if (hours > 0) return `${hours}h ago`;
  if (minutes > 0) return `${minutes}m ago`;
  return 'just now';
}

function getStatusLabel(status: Workflow['status']): string {
  switch (status) {
    case 'draft':
      return 'Draft';
    case 'published':
      return 'Published';
    case 'archived':
      return 'Archived';
    default:
      return 'Draft';
  }
}

// =============================================================================
// WorkflowCard Component
// =============================================================================

export function WorkflowCard({
  workflow,
  isSelected = false,
  onClick,
  onDelete,
}: WorkflowCardProps): React.JSX.Element {
  const nodeCount = workflow.nodes?.length ?? 0;
  const edgeCount = workflow.edges?.length ?? 0;
  const tags = workflow.tags ?? [];
  const displayTags = tags.slice(0, 3);
  const remainingTagCount = tags.length - 3;
  const status = workflow.status ?? 'draft';

  const handleDeleteClick = (e: React.MouseEvent) => {
    e.stopPropagation();
    onDelete?.();
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault();
      onClick();
    }
  };

  return (
    <article
      className={cardVariants({ state: isSelected ? 'selected' : 'default' })}
      onClick={onClick}
      onKeyDown={handleKeyDown}
      // biome-ignore lint/a11y/noNoninteractiveTabindex: Card is interactive (click to select)
      tabIndex={0}
      data-testid="workflow-card"
      data-selected={isSelected}
    >
      {/* Thumbnail / Preview */}
      <div className="relative aspect-video bg-canvas border-b border-border-muted overflow-hidden">
        {workflow.thumbnail ? (
          <img
            src={workflow.thumbnail}
            alt={`${workflow.name} preview`}
            className="w-full h-full object-cover"
          />
        ) : (
          <div className="absolute inset-0 flex items-center justify-center">
            <div className="flex flex-col items-center gap-2 text-fg-subtle">
              <ImageIcon className="h-8 w-8" weight="light" />
              <span className="text-xs">No preview</span>
            </div>
          </div>
        )}

        {/* AI Generated badge - top right of thumbnail */}
        {workflow.aiGenerated && (
          <div className="absolute top-2 right-2">
            <span
              className="inline-flex items-center gap-1 h-5 px-2 text-[10px] font-medium rounded-full bg-accent-muted text-accent border border-accent/30"
              title={workflow.aiModel ? `Generated by ${workflow.aiModel}` : 'AI generated'}
            >
              <Robot className="h-3 w-3" weight="fill" />
              AI
            </span>
          </div>
        )}

        {/* Status badge - top left of thumbnail */}
        <div className="absolute top-2 left-2">
          <span
            className={statusBadgeVariants({ status })}
            data-testid="workflow-status"
            data-status={status}
          >
            <span
              className={cn(
                'w-1.5 h-1.5 rounded-full bg-current',
                status === 'draft' && 'opacity-60'
              )}
            />
            {getStatusLabel(status)}
          </span>
        </div>
      </div>

      {/* Content */}
      <div className="p-4">
        {/* Header: Name and delete button */}
        <div className="flex items-start justify-between gap-2 mb-2">
          <h3
            className="text-sm font-semibold text-fg line-clamp-1"
            title={workflow.name}
            data-testid="workflow-name"
          >
            {workflow.name}
          </h3>
          {onDelete && (
            <Button
              variant="ghost"
              size="icon"
              onClick={handleDeleteClick}
              className="h-6 w-6 shrink-0 text-fg-muted hover:text-danger hover:bg-danger-muted opacity-0 group-hover:opacity-100 transition-opacity"
              aria-label={`Delete ${workflow.name}`}
              data-testid="workflow-delete-button"
            >
              <Trash className="h-3.5 w-3.5" />
            </Button>
          )}
        </div>

        {/* Description */}
        {workflow.description && (
          <p
            className="text-xs text-fg-muted line-clamp-2 mb-3"
            title={workflow.description}
            data-testid="workflow-description"
          >
            {workflow.description}
          </p>
        )}

        {/* Tags */}
        {tags.length > 0 && (
          <div className="flex items-center gap-1.5 flex-wrap mb-3" data-testid="workflow-tags">
            <Tag className="h-3 w-3 text-fg-subtle shrink-0" />
            {displayTags.map((tag) => (
              <span
                key={tag}
                className="inline-flex items-center h-5 px-1.5 text-[10px] font-medium rounded bg-surface-muted text-fg-muted"
              >
                {tag}
              </span>
            ))}
            {remainingTagCount > 0 && (
              <span className="text-[10px] text-fg-subtle">+{remainingTagCount} more</span>
            )}
          </div>
        )}

        {/* Stats: Node/Edge count */}
        <div
          className="flex items-center gap-4 text-xs text-fg-muted mb-3"
          data-testid="workflow-stats"
        >
          <span className="flex items-center gap-1">
            <span className="font-medium text-fg">{nodeCount}</span> nodes
          </span>
          <span className="flex items-center gap-1">
            <ArrowsLeftRight className="h-3 w-3" />
            <span className="font-medium text-fg">{edgeCount}</span> edges
          </span>
        </div>

        {/* Footer: Dates */}
        <div className="flex items-center justify-between text-[11px] text-fg-subtle pt-2 border-t border-border-muted">
          <span className="flex items-center gap-1" title={`Created: ${workflow.createdAt}`}>
            <Calendar className="h-3 w-3" />
            {formatRelativeTime(workflow.createdAt)}
          </span>
          <span className="flex items-center gap-1" title={`Updated: ${workflow.updatedAt}`}>
            <Clock className="h-3 w-3" />
            {formatRelativeTime(workflow.updatedAt)}
          </span>
        </div>
      </div>
    </article>
  );
}
